### ISSUE TITLE
macos installation error

### ISSUE THREAD

**Issue by ihubgit** [Xtrendence/FileDrop#16]
running big sur. Getting following error :
A JavaScript error occurred in the main process
Uncaught Exception:
Error: dlopen(/Applications/FileDrop.app/Contents/Resources/app/node_modules/leveldown/build/Release/leveldown.node, 1): no suitable image found.  Did find:
/Applications/FileDrop.app/Contents/Resources/app/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
/Applications/FileDrop.app/Contents/Resources/app/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:94:18)
at load (/Applications/FileDrop.app/Contents/Resources/app/node_modules/node-gyp-build/index.js:20:10)
at Object.<anonymous> (/Applications/FileDrop.app/Contents/Resources/app/node_modules/leveldown/binding.js:1:43)

**Comment by Xtrendence** [comment]
Hi, this would suggest the architecture of your device doesn't match the one you downloaded. If you have a Mac with an Apple Silicon chip, make sure you download the ARM64 version of FileDrop from the latest release. 

If neither macOS versions work, then please report back and I'll build it again in the next day or two. :)

**Comment by ihubgit** [comment]
Hi, it's an intel imac and i picked this version FileDrop.1.0.6.Mac.x64.dmg, which should be the proper one...

**Comment by Xtrendence** [comment]
Seems like `electron-builder` doesn't like building working x64 apps on ARM64 macOS devices. Oh well. I built it again on my old Intel Mac, so it should work fine now: https://github.com/Xtrendence/FileDrop/releases/download/V.1.0.6/FileDrop.1.0.6.Mac.x64.dmg

**Comment by ihubgit** [comment]
ok that seems to do the trick. I have it up and running now. It's normal the connection isn't secure in Firefox?
Is it possible for someone else to connect to my server from over the internet, not on the same LAN ? if so what would the procdure be in order to do file sharing ? This would be purely p2p right ?

**Comment by Xtrendence** [comment]
1) Yes that's normal, it's because localhost uses HTTP unless you go through a lot of hassle to install an SSL certificate and whatnot. Encryption is used on the client-side, meaning any files you send over LAN should be encrypted in such a way that other devices won't be able to intercept the data (using Wireshark for example) even without HTTPS.

2) Nobody should be able to connect to your server unless you have the port that FileDrop uses forwarded (3180). If you're not sure what this means, then you very likely don't have it forwarded as it's not a default port or anything that routers would forward by default. In any case, you can Google "what's my IP", put that in your browser's URL bar followed by `:3180` while FileDrop is running to ensure it can't be access that way. 

3) You can share files between devices on the same network by visiting the host's IP address followed by the port (the one displayed in the little window that opens when you run FileDrop). Technically, it's not P2P because the host running FileDrop is acting as a server, so files are always being sent to that device first before being passed on to another device. However, the way the encryption is implemented means that the server cannot read the data unless you actually meant to send the file to the server itself.

**Comment by ihubgit** [comment]
Hi thanks for the reply, could filedrop be used in a secure way for exchanging files over the Internet. I'm currently behind a corporate firewall so how could it be done ? In this scenario, can it have secure connections ?

**Comment by ihubgit** [comment]
ps are there mobile apps available for this ? (android)

**Comment by Xtrendence** [comment]
I don't think FileDrop suits that purpose honestly, especially because if you're behind a firewall, you probably can't forward any ports. Companies usually record the network activity of their employees, so using services that might trigger alarms isn't recommended. Even with HTTPS, they can see the domain name of the sites you visit and services you use. I'd say the best way to securely send/receive files would be one that can easily be disguised as a regular activity. For example, if you encrypt a 7Z archive and then use something as commonly used as Google Drive or DropBox to upload it and download it on the other end. By encrypting the archive, you ensure Google can't access the files, and by using Google Drive, you make what you're doing seem completely normal as people use popular cloud storage providers for everyday activities.

For mobile, I'd say do the same, so look for an archiver app that supports archive encryption, encrypt your files, then use the official Google Drive app to upload it.

**Comment by ihubgit** [comment]
thx for clearing that up. Last question for using filedrop inside LAN. Once the server is up, how does one "visiting the host's IP address followed by the port". Does the other person needs to install filedrop too or can he just use any browser ?

**Comment by Xtrendence** [comment]
They can use any browser to go to the host device's IP. So for example, if you install and run FileDrop on your laptop, then you can use your phone's browser to go to the IP of your laptop, and send files to it. Or, another example, you can be running FileDrop on your laptop, then go to the laptop's IP on both your phone and your desktop PC, and your phone and PC would be able to send files to each other without either of them having FileDrop installed.
