### ISSUE TITLE
unusable on MacOS

### ISSUE THREAD

**Issue by ihubgit** [Xtrendence/FileDrop#17]
Hi tried several times between two Macs running Big Sur.
First time using encryption, getting an undefined file with zero octets.
Using without encryption, nothing happens in destination's download folder.
No OS firewall running on machines, lulu in one and little snitch on destination, but not getting any alert and server says file transfer successful...

**Comment by Xtrendence** [comment]
Hi, that's very odd. If the devices see each other, then it's very likely not a firewall or even network issue as the file transfer uses the same sockets and methods to broadcast the client list and handle asking for permission to send a file etc. If encryption is disabled as well, then pretty much the only thing that could be the issue is somehow the browser can't read the file content when it's being uploaded. I've tested it with both an Intel and ARM64 Mac on Chrome without issues, so I think it's something to do with either your browser or FileDrop's ability to read file content on your system. 

What happens if you use your phone or another device that isn't running macOS to send a file to one of the Macs? If that works fine, then please make sure you're using Chrome, and that there isn't anything that is preventing your browser from reading files. Even though I don't think a firewall issue would be likely, try disabling those too and see if it makes a difference, but I'd be surprised if that's the issue.

**Comment by ihubgit** [comment]
hi, actually it was the browser that was the culprit. I was using Firefox. When using Chromium, the transfer works...
It might be a good thing though to be able to change the "open in browser" to "open in Chrome/Chromium", because otherwise i have to change my default browser to Chromium just to have it work, which is a bit cumbersome.
What would filedrop add to f.ex. a FOSS project such as LANdrop ?

**Comment by Xtrendence** [comment]
I'm glad it works! :)

I'll look into why it doesn't work on Firefox, because as far as I remember I didn't use anything exclusive to Chrome. As far as the "Open In Chrome" goes, I'll have to see if Electron allows an app to choose something other than the default application to open links. 

As for LANDrop, I just took a quick look and I don't think FileDrop provides anything that LANDrop doesn't. Ultimately FileDrop was developed as part of my university coursework, so I wasn't necessarily trying to solve a problem that existed. LANDrop is written in C++ as well, so it's a lot more lightweight and efficient. Perhaps the only two advantages I can think of with FileDrop are that HTML/CSS/JS are a lot easier for others to modify, so in terms of being open-source, the codebase is more accessible to the community. The other advantage being the interface, as I personally don't find LANDrop to be that good looking, but obviously appearance doesn't matter much for an app like this where you just want to send/receive files.
